export const SERVICES = [
  { icon: '💥', key: 'collision', label: 'Golpe / Colisión' },
  { icon: '🔧', key: 'mechanical', label: 'Mecánica' },
  { icon: '⚙️', key: 'tuning', label: 'Afinación' },
  { icon: '🛢️', key: 'oilChange', label: 'Cambio de aceite' },
  { icon: '🎨', key: 'fullPaint', label: 'Baño de Pintura' },
  { icon: '🖌️', key: 'panelPaint', label: 'Repintado (Piezas)' },
  { icon: '🔧', key: 'pdr', label: 'Varillaje (Granizo)' },
  { icon: '🛡️', key: 'bumperRepair', label: 'Reparación Fascias' },
  { icon: '✨', key: 'polishing', label: 'Pulido / Detailing' },
  { icon: '💡', key: 'headlightRestoration', label: 'Restauración Faros' },
  { icon: '⚙️', key: 'frameRepair', label: 'Banco / Chasis' },
  { icon: '🪟', key: 'glassReplacement', label: 'Cambio de Cristal' },
  { icon: '➕', key: 'other', label: 'OTRO SERVICIO...' },
]

export const ESTIMATED_TIMES = [
  '1 Día Hábil',
  '2 a 3 Días Hábiles',
  '1 Semana',
  '2 Semanas',
  'Más de 2 Semanas',
]

export const VEHICLE_BRANDS = [
  'Acura',
  'Alfa Romeo',
  'Audi',
  'Baic',
  'Bestune',
  'BMW',
  'Buick',
  'BYD',
  'Cadillac',
  'Changan',
  'Chery',
  'Chevrolet',
  'Chirey',
  'Chrysler',
  'Cupra',
  'Deepal',
  'Denza',
  'Dodge',
  'Dongfeng',
  'FAW',
  'Ferrari',
  'Fiat',
  'Ford',
  'GAC',
  'GMC',
  'GWM',
  'Haval',
  'Honda',
  'Hyundai',
  'Infiniti',
  'JAC',
  'JAECOO',
  'Jeep',
  'Jetour',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Mazda',
  'Mclaren',
  'Mercedes-Benz',
  'MG',
  'Mitsubishi',
  'Nissan',
  'Omoda',
  'Otro',
  'Peugeot',
  'Porsche',
  'RAM',
  'Renault',
  'Rivian',
  'Saic',
  'Seat',
  'Seres',
  'Skoda',
  'Smart',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
  'Zeekr',
]

export const UI_TEXT = {
  buttons: {
    addBodywork: '+ LABOR HOJALATERÍA',
    addMechanical: '+ AGREGAR MECÁNICA',
    addPaint: '+ PIEZA PINTURA',
    addPart: '+ AGREGAR REPUESTO',
    back: 'Volver',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    edit: 'Editar',
    generatePDF: 'Generar Cotización Profesional',
    newQuotation: '+ Nueva Cotización',
    save: 'Guardar Cotización',
    update: 'Actualizar Cotización',
    view: 'Ver',
  },
  labels: {
    balance: 'SALDO PENDIENTE',
    downPayment: 'ANTICIPO',
    estimatedTime: 'Tiempo Estimado',
    folio: 'FOLIO',
    piecesToWork: 'Piezas a Intervenir',
    total: 'TOTAL PRESUPUESTO',
  },
  placeholders: {
    bodyworkDescription: 'Descripción del trabajo de hojalatería',
    clientAddress: 'Ej. Calle Volcán Popocatépetl No. 513',
    clientEmail: 'Ej. cliente@email.com',
    clientName: 'Ej. Carlos Eduardo Ramírez López',
    clientPhone: 'Ej. 3339658258',
    mechanicalDescription: 'Descripción de la reparación mecánica',
    paintPart: 'Pieza a pintar',
    partDescription: 'Descripción del repuesto',
    vehicleColor: 'Ej. Gris Oxford',
    vehicleModel: 'Ej. Jetta 2019',
    vehiclePaintCode: 'Ej. NH-731P',
    vehiclePlates: 'Ej. ABC-123',
  },
  sections: {
    bodywork: 'Hojalatería',
    client: 'Datos del Cliente',
    mechanical: 'Mecánica',
    paint: 'Pintura',
    parts: 'Repuestos y Accesorios',
    services: 'Tipo de Servicio y Daño',
    vehicle: 'Datos del Vehículo',
    workshop: 'Perfil del Taller',
  },
}
